# Neural networks basics

In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

**Task 1.** Write a method for performing feed forward for a network with 2 input neurons, 3 hidden neurons with ReLU as the activation function, and 1 output neuron with no activation function. The interface of the method should be as follows:

    feed_forward_1(x, w1, w2)
    
where x is a numpy array of size 1x2, w1 is a numpy array of size 3x2 of weights from the input layer to the hidden layer, w2 is a numpy array of size 1x3. The result should be a single number.

As a helper function you can write the relu function:

    relu(x)
   
which takes a numpy array as input and applies the ReLU function element-wise.

Test it on 2-3 examples, calculate the result also with pen and paper by yourself (it's very important to do it at least once in your life!) and compare your results with the function results.

In [52]:
def temp(a):
    return a + 1

def relu(x):
    ########################
    # Write your code here #
    ########################
    if x > 0:
        return x
    return 0

def relu2(x):
    tempik = np.vectorize(relu)
    return tempik(x)

def feed_forward_1(x, w1, w2):
    ########################
    # Write your code here #
    ########################
    w1x = np.matmul(w1, x)
    reluw1x = relu2(w1x)
    w2reluw1x = np.matmul(w2, reluw1x)
    reluw2reluw1x = relu2(w2reluw1x)
    return reluw2reluw1x

def simpler(x):
    return x[0][0]


# Test

########################
# Write your code here #
########################
print(relu(3))
array = np.array([[1],[-2],[3]])
print(array)
blep = np.vectorize(relu)
arrayblep = blep(array)
print(arrayblep)
print(relu2(array))

w1 = np.array([[0.1, 0.2], [0.7, 0.3], [0.4, 0.3]])
print(w1)
w2 = np.array([[0.4, 0.2, 0.9]])
# w2 = np.array([[1, -1, 1]])
print(w2)
x = np.array([[0.9], [0.7]])
print(x)

print(feed_forward_1(x, w1, w2))
print(simpler(feed_forward_1(x, w1, w2)))

3
[[ 1]
 [-2]
 [ 3]]
[[1]
 [0]
 [3]]
[[1]
 [0]
 [3]]
[[0.1 0.2]
 [0.7 0.3]
 [0.4 0.3]]
[[0.4 0.2 0.9]]
[[0.9]
 [0.7]]
[[0.773]]
0.7730000000000001


**Task 2.** Write a method for performing feed forward for a network with 2 input neurons, 3 hidden neurons with sigmoid activation function, and 1 output neuron with sigmoid activation function. The interface of the method should be as follows:

    feed_forward_2(x, w1, w2)
    
where x is a numpy array of size 1x2, w1 is a numpy array of size 3x2 of weights from the input layer to the hidden layer, w2 is a numpy array of size 1x3. The result should be a single number.

As a helper function you can write the sigmoid function:

    sigmoid(x)
   
which takes a numpy array as input and applies the logistic function element-wise.

Test it on 2-3 examples. Try to estimate the result by hand and compare both results.

In [45]:
import math
def sigmoid(x):
    ########################
    # Write your code here #
    ########################
    return 1 / (1 + (math.exp(-x)))

def sigmoid2(x):
    tempik = np.vectorize(sigmoid)
    return tempik(x)

def feed_forward_2(x, w1, w2):
    ########################
    # Write your code here #
    ########################
    w1x = np.matmul(w1, x)
    reluw1x = sigmoid2(w1x)
    w2reluw1x = np.matmul(w2, reluw1x)
    reluw2reluw1x = sigmoid2(w2reluw1x)
    return reluw2reluw1x

# Test

########################
# Write your code here #
########################
print(sigmoid(1))
w1 = np.array([[0.1, 0.2], [0.7, 0.3], [0.4, 0.3]])
print(w1)
w2 = np.array([[0.4, 0.2, 0.9]])
# w2 = np.array([[1, -1, 1]])
print(w2)
x = np.array([[0.9], [0.7]])
print(x)

print(feed_forward_2(x, w1, w2))

0.7310585786300049
[[0.1 0.2]
 [0.7 0.3]
 [0.4 0.3]]
[[0.4 0.2 0.9]]
[[0.9]
 [0.7]]
[[0.71859015]]


**Task 3.** Write a method for performing feed forward for a network with 2 input neurons, 3 hidden neurons with relu activation, and 3 output neurons with no activation function but softmax applied to them. The interface of the method should be as follows:

    feed_forward_3(x, w1, w2)
    
where x is a numpy array of size 1x2, w1 is a numpy array of size 3x2 of weights from the input layer to the hidden layer, w2 is a numpy array of size 3x3. The result should be a numpy array of size 1x3.

As a helper function you can write the softmax function:

    softmax(x)
   
which takes a numpy array as input, applies softmax to it and returns a numpy array of the same size.

Test it on 2-3 examples. Try to estimate the result by hand and compare both results. Verify that the sum of output neurons is equal to 1.

In [59]:
def softmax(x):
    ########################
    # Write your code here #
    ########################
    suma = np.sum(np.exp(x))
    tempik = np.exp(x) / suma
    return tempik

def feed_forward_3(x, w1, w2):
    w1x = np.matmul(w1, x)
    reluw1x = relu2(w1x)
    w2reluw1x = np.matmul(w2, reluw1x)
    reluw2reluw1x = softmax(w2reluw1x)
    return reluw2reluw1x

# Test

########################
# Write your code here #
########################
print(sigmoid(1))
w1 = np.array([[0.1, 0.2], [0.7, 0.3], [0.4, 0.3]])
print(w1)
w2 = np.array([[0.4, 0.2, 0.9], [0.4, 0.8, 0.94], [0.2, 0.3, 0.5]])
# w2 = np.array([[1, -1, 1]])
print(w2)
x = np.array([[0.9], [0.7]])
print(x)

print(feed_forward_3(x, w1, w2))
#print(relu2(np.matmul(w1, x)))
#print(softmax(relu2(np.matmul(w1, x))))

0.7310585786300049
[[0.1 0.2]
 [0.7 0.3]
 [0.4 0.3]]
[[0.4  0.2  0.9 ]
 [0.4  0.8  0.94]
 [0.2  0.3  0.5 ]]
[[0.9]
 [0.7]]
[[0.2840535 ]
 [0.48104586]
 [0.23490064]]


**Task 4.** Write a method for calculating the squared error:

    se(y_bar, y)
    
where y_bar is a numpy array of predicted results and y is a numpy array of real values to be predicted.

Test it on the 2-3 examples you created for feed_forward_1 and find the SE with respect to real values chosen by hand. Experiment with several values to get a grip of how SE works.

In [61]:
def se(y_bar, y):
    ########################
    # Write your code here #
    ########################
    temp = y - y_bar
    tempik = (temp * temp)
    return np.sum(tempik)
    
# Test

########################
# Write your code here #
########################
a = np.array([0.4, 0.5, 0.6])
b = np.array([0.43, 0.58, 0.6])
print(se(a, b))

0.007299999999999991


**Task 5.** Write a method for calculating the cross-entropy loss:

    crossentropy(y_bar, y)
    
where y_bar is a numpy array of predicted results and y is a numpy array of real values to be predicted (y must contain one value of 1 and 0 on all other positions - just like in one-hot encoding).

Test it on the 2-3 examples you created for feed_forward_3 and find the cross-entropy with respect to vectors of real values chosen by hand. Experiment with several target vectors to get a grip of how cross-entropy works.

In [ ]:
def crossentropy(y_bar, y):
    ########################
    # Write your code here #
    ########################
    print()
    
# Test

########################
# Write your code here #
########################
y1 = [0, 0, 1, 0]
y2 = [1, 0, 0, 0]

**Task 6.** Write a method which calculates the error term for network 2:

    error_term(x, w1, w2, y)
    
where x is a numpy array of size 1x2, w1 is a numpy array of size 3x2 of weights from the input layer to the hidden layer, w2 is a numpy array of size 1x3, y is a float.

The solution is extremely simple - it's just the difference between y and the result of feed_forward_2. This task is solely to bring this notion to your attention.

Test it on the 2-3 examples you created for feed_forward_2 and several values of y (remember that the values of y should logically be in the interval [0-1], because you used the sigmoid activation which sends the network's results into this interval, technically turning them into probabilities).

In [ ]:
def error_term(x, w1, w2, y):
    ########################
    # Write your code here #
    ########################

# Test

########################
# Write your code here #
########################

**Task 7.** Write a method which calculates the derivative of the sigmoid function on every element of a numpy array:

    sigmoid_derivative(x)
    
where x is a numpy array. The result should have the same size as the input.

Use the formula:

<center>
$$
    \sigma'(x) = \sigma(x) (1 - \sigma(x))
$$
</center>

Verify this formula by differentiating the sigmoid function by hand.

Test the sigmoid_derivative method on a numpy array with several values (e.g. -3, -2, -1, 0, 1, 2, 3).

In [ ]:
def sigmoid_derivative(x):
    ########################
    # Write your code here #
    ########################

# Test

########################
# Write your code here #
########################

**Task 8.** Write a method for performing the backpropagation step for network 2. The method should have the following interface:

    backpropagate(x, w1, w2, y, alpha)
    
where x is a numpy array of size 1x2, w1 is a numpy array of size 3x2 of weights from the input layer to the hidden layer, w2 is a numpy array of size 1x3, y is a float, alpha is the learning rate. The method should return a tuple with updated matrices w1 and w2.

Test it on 2-3 examples. Test several values of the learning rate alpha on the same input to see how it affects the update step.

In [ ]:
def backpropagate(x, w1, w2, y, alpha):
    ########################
    # Write your code here #
    ########################
    return w1, w2

# Test

########################
# Write your code here #
########################

**Task 9.** Write a method for performing the backpropagation step for network 2 but without the activation function on the output neuron.

In [ ]:
def backpropagate_2(x, w1, w2, y, alpha):
    ########################
    # Write your code here #
    ########################
    return w1, w2

# Test

########################
# Write your code here #
########################